# ACCELERATOR_CLOSE = "Alt+F4"

# Edit accelerators
ACCELERATOR_UNDO = "Ctrl+Z"
ACCELERATOR_REDO = "Ctrl+Y"
ACCELERATOR_CUT = "Ctrl+X"
ACCELERATOR_COPY = "Ctrl+C"
ACCELERATOR_PASTE = "Ctrl+V"
ACCELERATOR_SELECT_ALL = "Ctrl+A"
