name: Bug 反馈
description: 当你在代码中发现了一个 Bug，导致应用崩溃或抛出异常，或者有一个组件存在问题，或者某些地方看起来不对劲。
title: "[Bug]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        感谢对项目的支持与关注。
  - type: checkboxes
    attributes:
      label: 这个问题是否已经存在？
      options:
        - label: 我已经搜索过现有的问题
          required: true
  - type: textarea
    attributes:
      label: 如何复现
      description: 请详细告诉我们如何复现你遇到的问题，如涉及代码，可提供一个最小代码示例，并使用三个反引号 ``` 包围
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true
  - type: textarea
    attributes:
      label: 预期结果
      description: 请告诉我们你预期会发生什么。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 实际结果
      description: 请告诉我们实际发生了什么。
    validations:
      required: true
  - type: textarea
    attributes:
      label: 截图或视频
      description: 如果可以的话，上传任何关于 bug 的截图。
      placeholder: "[在这里上传图片]"
  - type: dropdown
    id: operating-systems
    attributes:
      label: 操作系统
      description: 您当前正在哪个操作系统使用我们软件？
      multiple: true
      options:
        - Windows
        - macOS
        - HarmonyOS
        - KaihongOS
        - 统信 UOS
        - Deepin
        - 银河麒麟
        - Android
        - OpenHarmony
        - FreeBSD
        - 其他 Linux 发行版
        - 其他操作系统
        - 我不知道
    validations:
      required: true
  - type: dropdown
    id: package-types
    attributes:
      label: 软件包类型
      description: 您当前正在使用我们应用的什么软件包类型？
      multiple: true
      options:
        - Inno Setup 安装包 (*_setup.exe)
        - 便携包（压缩文件）(*_portable.zip)
        - Python ZIP 应用 (*_zipapp.pyzw)
        - 我不知道
    validations:
      required: true
