"""
This type stub file was generated by pyright.
"""

from typing import Any, NamedTuple, Optional, Tuple

class Padding(NamedTuple):
    left: Any
    top: Any
    right: Any
    bottom: Any
    def to_padx(self) -> Tuple[Any, Any]: ...
    def to_pady(self) -> Tuple[Any, Any]: ...

def parse_padding(padding) -> Optional[Padding]: ...
