name: Release App

on:
  release:
    types: [ published ]

permissions:
  contents: read

jobs:
  build:
    uses: ./.github/workflows/build.yml
    secrets: inherit
  release:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Download All Packages
        uses: actions/download-artifact@v4
        with:
          merge-multiple: true
      - name: Release Upload Assets
        uses: jaywcjlove/github-action-upload-assets@v1.1.1
        with:
          tag: ${{ github.event.release.tag_name }}
          asset-path: '["*_portable_windows.zip", "*_setup.exe", "vcf_generator_lite.pyzw"]'